### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [r-light/domic#1]
请问可以将应用发布在 F-Droid 上吗？

**Comment by r-light** [comment]
目前软件还处于测试阶段，不太稳定，等正式版发布后会考虑在github和F-Droid同步更新。

**Comment by linsui** [comment]
谢谢！

**Comment by linsui** [comment]
两年过去了，我又看到了这个项目。 :rofl: 请问现在考虑发布到 F-Droid 吗？
